/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.migalang_midterm_exam;

import java.awt.Color;

/**
 *
 * @author CL3-PC22
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButton3.setText("1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jButton4.setText("1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton5.setText("1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButton6.setText("1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jButton7.setText("1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jButton8.setText("1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton9.setText("1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jButton10.setText("2");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton11.setText("2");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jButton12.setText("2");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jButton13.setText("2");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jButton14.setText("2");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton15.setText("2");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jButton16.setText("2");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jButton17.setText("2");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton18.setText("2");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jButton19.setBackground(java.awt.Color.blue);
        jButton19.setForeground(java.awt.Color.black);
        jButton19.setText("Result");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jButton20.setBackground(java.awt.Color.red);
        jButton20.setForeground(java.awt.Color.black);
        jButton20.setText("Clear");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jLabel10.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 40, 20));

        jLabel2.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 30, 20));

        jLabel3.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 20, 20));

        jLabel4.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel5.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 30, 20));

        jLabel6.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel7.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 20, 20));

        jLabel8.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 20, 20));

        jLabel9.setForeground(java.awt.Color.red);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 20, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\CL3-PC22\\Downloads\\TICKTACK.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel1.setText("1");
        jButton1.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel4.setText("1");
        jButton4.setForeground(Color.red);
        }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel2.setText("1");
       jButton2.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel3.setText("1");
        jButton3.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel5.setText("1");
        jButton5.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel6.setText("1");
        jButton6.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel7.setText("1");
        jButton7.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel8.setText("1");
        jButton8.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
           int p1 = 1;
             
                
                 if (p1==1)
        {
        jLabel9.setText("1");
        jButton9.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
     
    {
    // Example: If any label has value "1" for player 1 or "2" for player 2
    if (jLabel1.getText().equals("1") && jLabel2.getText().equals("1") && jLabel3.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.yellow);
    } 
    else if (jLabel1.getText().equals("1") && jLabel5.getText().equals("1") && jLabel9.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.red);
    }
    else if (jLabel3.getText().equals("1") && jLabel5.getText().equals("1") && jLabel7.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.blue);
    }
    else if (jLabel1.getText().equals("1") && jLabel4.getText().equals("1") && jLabel7.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.white);
    }
    else if (jLabel2.getText().equals("1") && jLabel5.getText().equals("1") && jLabel8.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.gray);
    }
    else if (jLabel3.getText().equals("1") && jLabel6.getText().equals("1") && jLabel9.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.CYAN);
    }
    else if (jLabel4.getText().equals("1") && jLabel5.getText().equals("1") && jLabel6.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
        jButton19.setForeground(Color.DARK_GRAY);
    }
    else if (jLabel7.getText().equals("1") && jLabel8.getText().equals("1") && jLabel9.getText().equals("1"))
    {
        jLabel10.setText("PLAYER 1 WINS!");
    }
    else if (jLabel1.getText().equals("1") && jLabel2.getText().equals("2") && jLabel3.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel1.getText().equals("1") && jLabel4.getText().equals("2") && jLabel3.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel1.getText().equals("1") && jLabel5.getText().equals("2") && jLabel9.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel2.getText().equals("1") && jLabel5.getText().equals("2") && jLabel8.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel3.getText().equals("1") && jLabel5.getText().equals("2") && jLabel7.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel3.getText().equals("1") && jLabel6.getText().equals("2") && jLabel9.getText().equals("1"))
    {
        jLabel10.setText("DRAW");
    }
    else if (jLabel1.getText().equals("2") && jLabel2.getText().equals("2") && jLabel3.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel1.getText().equals("2") && jLabel5.getText().equals("2") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel1.getText().equals("2") && jLabel4.getText().equals("2") && jLabel7.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel2.getText().equals("2") && jLabel5.getText().equals("2") && jLabel8.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel3.getText().equals("2") && jLabel5.getText().equals("2") && jLabel7.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel3.getText().equals("2") && jLabel6.getText().equals("2") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel4.getText().equals("2") && jLabel5.getText().equals("2") && jLabel6.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    } else if (jLabel7.getText().equals("2") && jLabel8.getText().equals("2") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("PLAYER 2 WINS!");
    }
     else if (jLabel1.getText().equals("2") && jLabel2.getText().equals("1") && jLabel3.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel1.getText().equals("2") && jLabel5.getText().equals("1") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel1.getText().equals("2") && jLabel4.getText().equals("1") && jLabel7.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel2.getText().equals("2") && jLabel5.getText().equals("1") && jLabel8.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel3.getText().equals("2") && jLabel6.getText().equals("1") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel4.getText().equals("2") && jLabel5.getText().equals("1") && jLabel6.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
      else if (jLabel7.getText().equals("2") && jLabel8.getText().equals("1") && jLabel9.getText().equals("2"))
    {
        jLabel10.setText("DRAW");
    }
    
    
}

       
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel1.setText("2");
        jButton10.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel2.setText("2");
        jButton11.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel3.setText("2");
        jButton12.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel4.setText("2");
        jButton13.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel5.setText("2");
        jButton14.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel6.setText("2");
        jButton15.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel7.setText("2");
        jButton16.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel8.setText("2");
        jButton17.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         int p2 = 2;
             
                
                 if (p2==2)
        {
        jLabel9.setText("2");
        jButton18.setForeground(Color.blue);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
         jLabel2.setText("");
          jLabel3.setText("");
           jLabel4.setText("");
            jLabel5.setText("");
             jLabel6.setText("");
              jLabel7.setText("");
               jLabel8.setText("");
                jLabel9.setText("");
                jLabel10.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
